# Generated by Django 4.1.3 on 2022-11-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
