# Generated by Django 4.1.1 on 2022-12-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
